package com.ridvanozcan.androidbaseapp.util.color

import androidx.compose.ui.graphics.Color

data class BaseColor(val color: Color)

object BaseLightColor {
    internal val Primary = BaseColor(Color(0xFF07AC92))
    internal val Secondary = BaseColor(Color(0xFF07AC92))
    internal val Tertiary = BaseColor(Color(0xFF07AC92))
    internal val Basement = BaseColor(Color(0xFFF7F7F7))
    internal val Surface = BaseColor(Color(0xFFFFFFFF))
    internal val Elevation = BaseColor(Color(0xFFF2F2F2))
    internal val Elevation1 = BaseColor(Color(0xFFE0E0E0))
    internal val Elevation2 = BaseColor(Color(0xFFCFCABF))
    internal val Elevation3 = BaseColor(Color(0xFFCCC5B8))
    internal val Elevation4 = BaseColor(Color(0xFFBFB6A6))
    internal val TextFocus = BaseColor(Color(0xFF070910))
    internal val TextSecondary = BaseColor(Color(0xFF8B8B8B))
    internal val TextTertiary = BaseColor(Color(0xFFBFBFBF))
    internal val IconFocus = BaseColor(Color(0xFF070910))
    internal val IconInactive = BaseColor(Color(0xFF707070))
    internal val IconDisabled = BaseColor(Color(0xFFBFBFBF))
    internal val SegmentActive = BaseColor(Color(0xFF131313))
    internal val InverseSwap = BaseColor(Color(0xFFFFFFFF))
    internal val InverseFocus = BaseColor(Color(0xFF000000))
    internal val PureWhite = BaseColor(Color(0xFFFFFFFF))
    internal val PureBlack = BaseColor(Color(0xFF000000))
    internal val Action01 = BaseColor(Color(0xFF6A992C))
    internal val Action02 = BaseColor(Color(0xFFA83A38))
    internal val Action03 = BaseColor(Color(0xFFDB8500))
    internal val Action01Opacity20 = BaseColor(BaseDarkColor.Action01.color.copy(0.2f))
    internal val Action02Opacity20 = BaseColor(BaseDarkColor.Action02.color.copy(0.2f))
    internal val Action03Opacity20 = BaseColor(BaseDarkColor.Action03.color.copy(0.2f))
    internal val Action01Opacity10 = BaseColor(BaseDarkColor.Action01.color.copy(0.1f))
    internal val Action02Opacity10 = BaseColor(BaseDarkColor.Action02.color.copy(0.1f))
    internal val Action03Opacity10 = BaseColor(BaseDarkColor.Action03.color.copy(0.1f))
}

object BaseDarkColor {
    internal val Primary = BaseColor(Color(0xFF07AC92))
    internal val Secondary = BaseColor(Color(0xFF07AC92))
    internal val Tertiary = BaseColor(Color(0xFF245956))
    internal val Basement = BaseColor(Color(0xFF050A0A))
    internal val Surface = BaseColor(Color(0xFF070D0D))
    internal val Elevation = BaseColor(Color(0xFF0F1D1D))
    internal val Elevation1 = BaseColor(Color(0xFF152A29))
    internal val Elevation2 = BaseColor(Color(0xFF152728))
    internal val Elevation3 = BaseColor(Color(0xFF173434))
    internal val Elevation4 = BaseColor(Color(0xFF245956))
    internal val TextFocus = BaseColor(Color(0xFFE7FEFA))
    internal val TextSecondary = BaseColor(Color(0xFF5D8E89))
    internal val TextTertiary = BaseColor(Color(0xFFBFBFBF))
    internal val IconFocus = BaseColor(Color(0xFFE7FEFA))
    internal val IconInactive = BaseColor(Color(0xFF5D8E89))
    internal val IconDisabled = BaseColor(Color(0xFF245956))
    internal val SegmentActive = BaseColor(Color(0xFF152728))
    internal val InverseSwap = BaseColor(Color(0xFF000000))
    internal val InverseFocus = BaseColor(Color(0xFFFFFFFF))
    internal val PureWhite = BaseColor(Color(0xFFFFFFFF))
    internal val PureBlack = BaseColor(Color(0xFF000000))
    internal val Action01 = BaseColor(Color(0xFF6A992C))
    internal val Action02 = BaseColor(Color(0xFFAD403E))
    internal val Action03 = BaseColor(Color(0xFFFFAC2B))
    internal val Action01Opacity20 = BaseColor(Action01.color.copy(0.2f))
    internal val Action02Opacity20 = BaseColor(Action02.color.copy(0.2f))
    internal val Action03Opacity20 = BaseColor(Action03.color.copy(0.2f))
    internal val Action01Opacity10 = BaseColor(Action01.color.copy(0.1f))
    internal val Action02Opacity10 = BaseColor(Action02.color.copy(0.1f))
    internal val Action03Opacity10 = BaseColor(Action03.color.copy(0.1f))
}